### ISSUE TITLE
Words in poem-game_words.txt categorized with typos?

### ISSUE THREAD

**Issue by as37267** [Skull217/DDLCtVN#10]
Not all words in poem-game_words.txt are in the right categories.

Examples:

#Sayori's winning words
dark,2,1,0,3 // weighted in points as Monika's word
together,2,0,1,3 //same
charm,1,2,0,3
beauty,0,2,1,3
special,1,2,0,3
music,1,2,0,3
extraordinary,0,2,1,3

Did you repurposed words as Monika's? Then it is fit to move them to their respective category in the file. Though it may not be a functional bug, I do want to attract your attention to it so everything still works as intended.

Thank you!

**Comment by Skull217** [comment]
I'll be sure to fix this in latest. Thanks!
