### ISSUE TITLE
Installation (Support for those who can't install/run the game)

### ISSUE THREAD

**Issue by Zanther123** [Skull217/DDLCtVN#13]
I am not an official supporter of this Mod but i loved this Mod and i felt bad when people couldn't get it to run so i am here to help out the Mod devs as best as i can so if you can not reach a Mod dev on running or installing the game please consider reaching me if necessary.

**Comment by dbomb424** [comment]
So I keep getting the error: 
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'mod_assets/poem-game_words.txt'.

I copied all the files to the game folder, and 'mod_assets/poem-game_words.txt' is in there o not sure why it can't find it.

**Comment by Zanther123** [comment]
Was this during the game or when you installed it and first tried to start up the game because there is a huge difference in results

**Comment by megasizoreman** [comment]
hay that you?

**Comment by Zanther123** [comment]
yep

**Comment by megasizoreman** [comment]
ok

**Comment by Zanther123** [comment]
alright so what is your problem again

**Comment by megasizoreman** [comment]
how to install it

**Comment by Zanther123** [comment]
so it says on the top right of the list Clone or Download right

**Comment by megasizoreman** [comment]
yeah and i have it downloaded it

**Comment by Zanther123** [comment]
alright im ganna make a list of all the steps to do so give me a minute

**Comment by megasizoreman** [comment]
i think i know what to do though

**Comment by megasizoreman** [comment]
go to the game folder and put those in there right?

**Comment by Zanther123** [comment]
yes

**Comment by Zanther123** [comment]
did it work?

**Comment by megasizoreman** [comment]
i havn't done it yet i was waiting for you sorry

**Comment by megasizoreman** [comment]
i think i got it

**Comment by megasizoreman** [comment]
normal VN?

**Comment by megasizoreman** [comment]
right?

**Comment by Zanther123** [comment]
yep

**Comment by megasizoreman** [comment]
then i got it thanks

**Comment by Zanther123** [comment]
no problem

**Comment by megasizoreman** [comment]
the start seems the same as normal

**Comment by megasizoreman** [comment]
is there any changes in the main story?

**Comment by megasizoreman** [comment]
like no killing from monika?

**Comment by dbomb424** [comment]
I got that message after I put the mod files into the game files and tried to start it for the first time

**Comment by Zanther123** [comment]
(this is if you are using Steam) ok so go into the the Doki Doki Literature Club folder and delete everything, then redownload Doki Doki Literature Club (from steam). Then redownload the mod files and move them into the "game" folder in the Doki Doki Literature Club folder.

**Comment by Zanther123** [comment]
If that doesn't work than you are either not doing it right, (Not saying that you are doing it wrong just saying it is a possibility) your platform isn't compatible, or the mod is not working right (if it is not working right and i can not fix it you need to get help from Skull217 because he knows alot more about the mod then me)

**Comment by dbomb424** [comment]
I got it thank you so much!

**Comment by Zanther123** [comment]
no problem

**Comment by Blitz00270** [comment]
ive been working on trying to run the program all day and i havent had any luck, i tried what you said on here and it didnt work but i have same error. here it is anyway
While running game code:
File "game/DDLCtVN-1.4.9/script-poemgame.rpy", line 1, in script
﻿init python:
File "game/DDLCtVN-1.4.9/script-poemgame.rpy", line 20, in
with renpy.file('mod_assets/poem-game_words.txt') as wordfile:
IOError: Couldn't find file 'mod_assets/poem-game_words.txt'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
File "D:\Steam\steamapps\common\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
renpy.main.main()
File "D:\Steam\steamapps\common\Doki Doki Literature Club\renpy\main.py", line 419, in main
game.context().run(node)
File "game/DDLCtVN-1.4.9/script-poemgame.rpy", line 1, in script
﻿init python:
File "D:\Steam\steamapps\common\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
File "D:\Steam\steamapps\common\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
exec bytecode in globals, locals
File "game/DDLCtVN-1.4.9/script-poemgame.rpy", line 20, in
with renpy.file('mod_assets/poem-game_words.txt') as wordfile:
File "D:\Steam\steamapps\common\Doki Doki Literature Club\renpy\exports.py", line 1980, in file
return renpy.loader.load(fn)
File "D:\Steam\steamapps\common\Doki Doki Literature Club\renpy\loader.py", line 543, in load
raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'mod_assets/poem-game_words.txt'.

**Comment by Blitz00270** [comment]
all i want is a date with yuri ;-;

**Comment by megasizoreman** [comment]
lol i want one with natsuki

**Comment by Zanther123** [comment]
Sorry for getting to this so late i just forgot to get to it but you need to either skip it if you can or (if you have it on Steam) you need to delete every file in the game and uninstall the game, then reinstall the game and and put all the mods in the game file again and hopefully it should fix the file issue but make sure you put every file into the game file and no other file or else it might not work

**Comment by Zanther123** [comment]
Alright so this is the end of my support i have to much to do these days and so i cant keep doing this so i am sorry for those who can't run the game but im shutting this down
