### ISSUE TITLE
uncaught exeption occured?

### ISSUE THREAD

**Issue by BERUI** [Skull217/DDLCtVN#14]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/splash.rpy", line 365, in script
    return
Exception: Could not find return label (u'D:\\Documents\\DDLC\\DDLC/game/script.rpy', 1475534846, 134).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/splash.rpy", line 365, in script
    return
  File "C:\Users\Inesp\Desktop\DDLC-1.1.0-pc\renpy\ast.py", line 1376, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "C:\Users\Inesp\Desktop\DDLC-1.1.0-pc\renpy\execution.py", line 552, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'D:\\Documents\\DDLC\\DDLC/game/script.rpy', 1475534846, 134).

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Doki Doki, The Normal VN! 1.4.9

**Comment by Zanther123** [comment]
Did this happen durring the game or when you tried to open the game

**Comment by Skull217** [comment]
Try deleting your firstrun?
