### ISSUE TITLE
Sayori is still hanging :V

### ISSUE THREAD

**Issue by IlywI** [Skull217/DDLCtVN#4]
![image](https://user-images.githubusercontent.com/23725018/36520984-4939421a-17cf-11e8-9b50-89ee4641b49f.png)

Maybe change the code a bit so that the image doesnt get shown?

**Comment by Skull217** [comment]
you say that as if this wasn't intentional

**_;)_**

**Comment by Alpha-Hedge** [comment]
Why leave that picture there if this is supposed to turn DDLC into a normal visual novel? Doesn't that take away the whole point?
