### ISSUE TITLE
Please explain this error...

### ISSUE THREAD

**Issue by Alucard3600** [Skull217/DDLCtVN#6]
I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.

The label start is defined twice, at
  File "game/script.rpy", line 4 and
  File "game/script2.rpy", line 4.

Ren'Py Version: Ren'Py 6.99.12.4.2187

**Comment by Skull217** [comment]
delete scripts.rpa

**Comment by Alucard3600** [comment]
worked great! thanks.

**Comment by SmartiePlays** [comment]
I appear to be getting this problem too, even though I deleted the scripts.rpa
