### ISSUE TITLE
Slight Bug...Thing.

### ISSUE THREAD

**Issue by Sp1cyB01** [Skull217/DDLCtVN#8]
Hello, Skull217. I have to give my sincerest thanks to you, as you fix most issues as they pop up. I am writing another issue, unfortunately. On a game script, there is a ceaseless failure of  poemWin == "s". I tried to fix it myself, and failed. Please fix this, but if you can't, that's fine. 

                                                                         -Sincerely, Me.

**Comment by Skull217** [comment]
Make sure you downloaded the release and not the experimental. that's the only reason I would see that happening.
