### ISSUE TITLE
Game returns to title screen after certain point

### ISSUE THREAD

**Issue by tophatsnake** [Skull217/DDLCtVN#9]
Pardon me if I'm just being ignorant and missing something, but I couldn't find anything on it or anyone with a similar issue. If I'm just missing something obvious then please let me know, but on the sayori route when she's on the bed with you after she comes over for your 6 month anniversary, she'll get to the point of saying "Hey [Player]? We are on your bed.." and then a couple dialogue lines later it transitions to the front of the house and then fades back to the main menu with no warning. This doesn't seem like it'd be something intentional so I was just wondering if I made a mistake somewhere or if my game is just bugging out.

**Comment by ddlcsayori** [comment]
I'm having this exact same issue. Did you find a fix?

**Comment by TriniTDM** [comment]
He seems to have made a "To Be Continued" gag every time you're about to "do" your girlfriend.
